# Change these first
owner: banahosting # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Banahosting
    url: https://banahosting.com
  - name: Ovh.es
    url: https://ovh.es

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Banahosting.com** Uptime Monitoring"
  introMessage: **real-time** status from [GitHub repository](https://manage.banahosting.com/aff.php?aff=2631). No server required. [**More info here**](https://manage.banahosting.com/aff.php?aff=2631)
  navbar:
    - title: Status
      href: /
    - title: Discount
      href: https://manage.banahosting.com/aff.php?aff=2631

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
